# Generated by Django 4.2.7 on 2023-11-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob_dokoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_data', models.DateField(auto_created=True)),
                ('book_name', models.CharField(max_length=50)),
                ('book_after', models.CharField(max_length=50)),
                ('book_janr', models.CharField(max_length=30)),
            ],
        ),
    ]
